// ==========================================
// AUTO-GENERATED CATALOG DATA - DO NOT EDIT
// Generated by update_catalog.py
// ==========================================

window.POP_CHARM_CATALOG = {
  "pearls300": [
    "pearls/300/WhatsApp Image 2026-06-20 at 5.13.03 PM.jpeg",
    "pearls/300/WhatsApp Image 2026-06-20 at 5.13.04 PM.jpeg",
    "pearls/300/WhatsApp Image 2026-06-20 at 6.57.15 PM.jpeg"
  ],
  "pearls450": [
    "pearls/450/WhatsApp Image 2026-06-22 at 7.49.21 PM.jpeg"
  ],
  "keychains": [
    "pearls/keychains/WhatsApp Image 2026-06-23 at 6.11.47 PM.jpeg",
    "pearls/keychains/WhatsApp Image 2026-06-23 at 6.11.50 PM.jpeg",
    "pearls/keychains/WhatsApp Image 2026-06-23 at 6.19.16 PM.jpeg",
    "pearls/keychains/WhatsApp Image 2026-06-23 at 6.47.13 PM.jpeg"
  ]
};
