import os
import json

def generate_catalog():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    pearls_300_dir = os.path.join(base_dir, "pearls", "300")
    pearls_450_dir = os.path.join(base_dir, "pearls", "450")
    keychains_dir = os.path.join(base_dir, "pearls", "keychains")

    allowed_extensions = {".png", ".jpg", ".jpeg", ".webp", ".gif"}

    def get_images_from_dir(directory, relative_prefix):
        if not os.path.exists(directory):
            print(f"Warning: Directory not found at {directory}")
            return []
        
        images = []
        # List files and sort them alphabetically
        for filename in sorted(os.listdir(directory)):
            ext = os.path.splitext(filename)[1].lower()
            if ext in allowed_extensions:
                # We save relative path with forward slashes for HTML/JS consistency
                rel_path = f"{relative_prefix}/{filename}"
                images.append(rel_path)
        return images

    pearls_300 = get_images_from_dir(pearls_300_dir, "pearls/300")
    pearls_450 = get_images_from_dir(pearls_450_dir, "pearls/450")
    keychains = get_images_from_dir(keychains_dir, "pearls/keychains")

    catalog_data = {
        "pearls300": pearls_300,
        "pearls450": pearls_450,
        "keychains": keychains
    }

    output_path = os.path.join(base_dir, "catalog_data.js")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("// ==========================================\n")
        f.write("// AUTO-GENERATED CATALOG DATA - DO NOT EDIT\n")
        f.write("// Generated by update_catalog.py\n")
        f.write("// ==========================================\n\n")
        f.write("window.POP_CHARM_CATALOG = ")
        f.write(json.dumps(catalog_data, indent=2))
        f.write(";\n")
        
    print(f"Successfully updated catalog_data.js with:")
    print(f"  - Rs. 300 Pearls: {len(pearls_300)} images")
    print(f"  - Rs. 450 Pearls: {len(pearls_450)} images")
    print(f"  - Keychains: {len(keychains)} images")

if __name__ == "__main__":
    generate_catalog()
